import { PrismaClient } from "@prisma/client";
import { hash } from "bcryptjs";
import { writeFileSync } from "fs";
import { join } from "path";

const prisma = new PrismaClient();

const USERS = [
  { fullName: "Alice Morgan",  email: "alice.morgan@firm.com",  password: "Alice@Pass1",  department: "Finance"     },
  { fullName: "Bob Chen",      email: "bob.chen@firm.com",      password: "Bob@Pass1",    department: "Legal"       },
  { fullName: "Carol Smith",   email: "carol.smith@firm.com",   password: "Carol@Pass1",  department: "Operations"  },
  { fullName: "David Kumar",   email: "david.kumar@firm.com",   password: "David@Pass1",  department: "Finance"     },
  { fullName: "Emma Johnson",  email: "emma.johnson@firm.com",  password: "Emma@Pass1",   department: "Operations"  },
];

async function main() {
  const role = await prisma.role.findUnique({ where: { name: "operations" } });
  if (!role) throw new Error("Operations role not found. Run `pnpm prisma:seed` first.");

  const lines: string[] = [
    "Dummy user credentials (operations role)",
    "Generated by src/prisma/seed-dummy-users.ts",
    "=========================================",
    "",
  ];

  for (const u of USERS) {
    const passwordHash = await hash(u.password, 12);
    await prisma.user.upsert({
      where: { email: u.email },
      update: { passwordHash, forcePasswordChange: false, isActive: true },
      create: {
        fullName: u.fullName,
        email: u.email,
        passwordHash,
        roleId: role.id,
        department: u.department,
        forcePasswordChange: false,
      },
    });
    lines.push(u.fullName);
    lines.push(`  Email:      ${u.email}`);
    lines.push(`  Password:   ${u.password}`);
    lines.push(`  Department: ${u.department}`);
    lines.push("");
    console.log(`upserted: ${u.email}`);
  }

  const outPath = join(process.cwd(), "dummy-users.txt");
  writeFileSync(outPath, lines.join("\n"), "utf8");
  console.log(`\nCredentials saved to: ${outPath}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
